#ifndef GLOBAL_H
#define GLOBAL_H

typedef enum {
    REGISTERED_EMPLOYEE,
    REGISTERED_MEMBER,
    REGISTERED_MILITARY_VETERAN,
}PersonType;

typedef enum {
    ADMINISTER_USER,
    ADMINISTER_EMPLOYEE,
    ADMINISTER_MEMBER,
    ADMINISTER_MILITARY_VETERAN,
}AdminMode;

typedef enum {
    AUTH,
    GET_MEMBER_DETAILS,
    GET_MEMBER_FINGERPRINTS,
    POST_MEMBER_FINGERPRINTS,
    GET_MEMBER_PORTRAIT,
    POST_MEMBER_PORTRAIT,
    GET_USER_DETAILS,
    GET_USER_FINGERPRINTS,
    GET_USER_PORTRAIT,
    GET_EMPLOYEE_DETAILS,
    GET_EMPLOYEE_FINGERPRINTS,
    GET_EMPLOYEE_PORTRAIT,
    POST_EMPLOYEE_FINGERPRINTS,
    POST_EMPLOYEE_PORTRAIT,
    GET_MILITARY_VETERAN_DETAILS,
    GET_MILITARY_VETERAN_FINGERPRINTS,
    POST_MILITARY_VETERAN_FINGERPRINTS,
    GET_MILITARY_VETERAN_PORTRAIT,
    POST_MILITARY_VETERAN_PORTRAIT,
    POST_USER_PORTRAIT,
    POST_USER_FINGERPRINTS

}TransmissionMode;

typedef enum {

    RIGHT_THUMB,
    RIGHT_INDEX,
    RIGHT_MIDDLE,
    RIGHT_RING,
    RIGHT_LITTLE,

    LEFT_THUMB,
    LEFT_INDEX,
    LEFT_MIDDLE,
    LEFT_RING,
    LEFT_LITTLE,

    UNKNOWN_TYPE,

} FingerType;

#endif // GLOBAL_H
