#ifndef GLOBAL_H
#define GLOBAL_H

typedef enum {
    REGISTERED_EMPLOYEE,
    REGISTERED_MEMBER
}PersonType;

typedef enum {
    AUTH,
    GET_MEMBER_DETAILS,
    GET_MEMBER_FINGERPRINTS,
    POST_MEMBER_FINGERPRINTS,
    GET_MEMBER_PORTRAIT,
    POST_MEMBER_PORTRAIT,
    GET_USER_DETAILS,
    GET_USER_FINGERPRINTS,
    GET_USER_PORTRAIT
}TransmissionMode;

typedef enum {

    RIGHT_THUMB,
    RIGHT_INDEX,
    RIGHT_MIDDLE,
    RIGHT_RING,
    RIGHT_LITTLE,

    LEFT_THUMB,
    LEFT_INDEX,
    LEFT_MIDDLE,
    LEFT_RING,
    LEFT_LITTLE,

    UNKNOWN_TYPE,

} FingerType;

#endif // GLOBAL_H
